version: '3'

services:
  express-ts:
    environment:
      - NODE_ENV=dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
    container_name: express-ts
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev
